# Generated by Django 4.2.7 on 2023-12-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_appointmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.appointmenttype')),
            ],
        ),
    ]
