# Generated by Django 4.2.7 on 2024-01-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_appointment_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
