# Generated by Django 4.2.7 on 2023-12-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_documento_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='credit_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='payments_confirmations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='plates_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='unit_details',
            field=models.BooleanField(default=True),
        ),
    ]
